### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by kaaholst**
Fix songs not ordered in 1.2.6

### CODE REVIEW

**Comment by kaaholst** [comment]
I have added some more fixes to this pull request
- Fix some download problems and add logging info when it fails. It don't think it fixes the root cause of the crashlytics indidents, but hopefully the new log-info can help.
- Fix issue 54 (and 86)
- Disable list items which performs no action in onItemSelected.
- Fix a bug when building the view for the context menu button.

**Comment by nikclayton** [comment]
Hi Kurt,

I'm (hopefully) going to have a bit more time over the next few weeks (transatlantic flights with not much else to do :-) ) to catch up on a bunch of this stuff.

In re "errors in the log every time Crashlytics were called", can you be more specific? I don't recall ever seeing anything in the logs when I was debugging.

In re "stripping android.util.Log calls in production", the existing proguard configs do that (at least, they certainly should do, and whenever I'm doing pre-release testing on non-debug builds I never see any Squeezer output in the log.

Timber's been on my list of things to consider for a while, I'll take a look.

In re "two versus one call from application code", I'm thinking that:

- Because we don't want all logs going to Crashlytics (or at least, I don't think we do, since we log a lot of stuff in the app, and I'm not sure I'm comfortable with the idea of shipping info like that off the device) and, 

- The vast majority of our logging calls are local, and

- I think it's OK that calls to log-off-the-device functionality look different in the code (if nothing else, it's a strong hint to the programmer that this is a different type of log, and to pay attention to what's being logged)

So I think it's OK that we have a very few places where there is a second call to log something that can leave the device.

I see you've made a number of new changes since I last looked at this as well. So what I'll do is start the work of merging them in, but I'll not include this specific change for the moment so we can keep talking about it as necessary.  With a bit of luck I should be able to publish a new beta some time in the second week of March.

**Comment by kaaholst** [comment]
The errors in the log "*E/Crashlytics﹕ Crashlytics must be initialized by calling Crashlytics.start(Context) prior to logging exceptions.*" come from calls to *Crashlytics.log* because of this in HomeActivity.java:
    if (!BuildConfig.DEBUG) {
        Crashlytics.start(this);
    }
This is the motivation (besides encapsulation) for the Logger class. Otherwise each call to *Crashlytics.log* will have to be made conditional by *if (!BuildConfig.DEBUG) ...*.

About the two versus one call I agree that remote logging should look different, and that it's very rare. But I still think that
    *RemoteLogger.log(...) // Log to a remote server on release builds and locally on debug builds.*
Is superior to:
    *Crashlytics.log(...) // Log to a remote server on release builds and do nothing on debug builds.*
    *Log.w(...) // Log locally on debug builds and do nothing on release builds.*

However as it is very rare, it is not a fundamental issue for me.

**Comment by kaaholst** [comment]
I have added a commit which fixes [issue 90](https://code.google.com/p/android-squeezer/issues/detail?id=90).

While at it I also added support for some more icon url's returned by recent servers.

I would like to have this particular issue ready in a beta version as soon as possible, because users which have updated to LMS 7.8.1 or later currently can't use internet radio.

**Comment by nikclayton** [comment]
On 6 March 2015 at 00:33, Kurt Aaholst <notifications@github.com> wrote:

> I have added a commit which fixes issue 90
> <https://code.google.com/p/android-squeezer/issues/detail?id=90>.
>
> While at it I also added support for some more icon url's returned by
> recent servers.
>
> I would like to have this particular issue ready in a beta version as soon
> as possible, because users which have updated to LMS 7.8.1 or later
> currently can't use internet radio.
>
I think I'm up to date on the develop branch now, and have merged the
connection-management and connection-state branches in.

I'm flying back to Europe today, so I'll cut a new beta later this week.

**Comment by kaaholst** [comment]
Great, thanks :-)

2015-03-15 20:45 GMT+01:00 Nik Clayton <notifications@github.com>:

**Pull request merged**
