### PR TITLE
Player list now sorted case insensitive

### PR DESCRIPTION
**Pull request by Gerrelt**
Player list is now sorted case insensitive, in drop down box and in player settings (sync) list.

### CODE REVIEW

**Comment by nikclayton** [comment]
Hi. I'm going to start looking at this, but it would be really helpful if in future (don't bother about it for this merge, I'll unpick it) you kept functional separate changes in to different pull requests. Thanks!

**Comment by Gerrelt** [comment]
Thank you! Yeah, I am a total GIT noob, so I blame it on inexperience.. :-)

**Comment by nikclayton** [comment]
I take it back. I don't think there's a way that I can split this in to independent commits without everything appearing to be committed by me.

I can either do that (I'll add attribution in the commit messages, obviously), or if you'd prefer, you can try and create branches for the work that you've done and cherry pick the existing commits on to those branches. Then I can merge from them.

Up to you. If you'd like to try the latter, could you try doing the following:

First, get the latest copy of my repo, switch to the develop branch, and make sure you're up to date with it. That should be the following commands.

```shell
git fetch nikclayton
git checkout develop
git pull
```

Now, you need to create one branch for each logical set of changes. Looking at the commits so far I think there's two sets, one for the next/prev buttons, and one for the player sorting, so that's two branches, we'll call `prev-next` and `player-sort`. Both of those will branch from `develop`:

```shell
git branch prev-next develop
git branch player-sort develop
```

Then you have to change in to those branches, and cherry pick the commits you want to appear in them. That should be something like:

```shell
git checkout prev-next
git cherry-pick -n 1b87d41
# Review the change, and "git commit" if it looks good
```

```shell
git checkout player-sort
git cherry-pick -n 9897684
# Review the change, and "git commit" if it looks good
git cherry-pick -n 91d754a
# Review the change, and "git commit" if it looks good
git cherry-pick -n 9881c5f
# Review the change, and "git commit" if it looks good
```

If I've got those commit numbers right (please double check them, and the results before you commit) that should give you two branches with the changes on them.

You can now push them (`git checkout prev-next && git push; git checkout player-sort && git push`) to get them up to GitHub. And from there, you can create two new pull requests, one from each of the branches.

Once you've done that, I can merge them in to my repository, and the attribution for the commits will clearly show your authorship.

This is also the model to use for any other contributions you'd like to make in the future -- sync to `develop`, create a branch for the change in there, and commit in that branch. If you've multiple independent changes to make, make sure that they happen in different branches to make merging easier.

Hope that's helpful.

**Comment by Gerrelt** [comment]
Yes, that was very helpfull! Thank you very much, I couldn't have done it without it. I now created two new pull requests, each only containing the changes for the specific functionality. I hope I did it right.
Now things are a bit more clear concerning git, and I will save this as a reference for future changes.

**Comment by nikclayton** [comment]
Almost right -- if I look at #188 and #189 they want to merge in to the `master` branch. That won't work, since `master` deliberately lags `develop`.

If you can reframe them so they're requests to merge in to `develop` everything should go cleanly.

If you haven't already seen it, check out https://github.com/nikclayton/android-squeezer/blob/master/CONTRIBUTING.md. The post at http://nvie.com/posts/a-successful-git-branching-model/ might also be helpful.

Let me know if that makes sense.

If it doesn't, don't worry -- I've just cloned your repository, and because you have these changes on two separate branches I can merge them cleanly from there.

**Comment by Gerrelt** [comment]
I've rebased them to develop, which was a lot easier then I thought. :-)
Please check if it's allright now.

And thanks for the links, I will study them. 
I must say, GIT is quite a bit harder to learn then any of the version managament systems I've had experience with. One of the bigger hurdles is that the terminology is a bit confusing, some things are called the same as in other VCS's, but do something different.

**Comment by nikclayton** [comment]
https://xkcd.com/1597/ :-)

**Comment by Gerrelt** [comment]
:-)  hahaha... xkcd rules!

**Comment by nikclayton** [comment]
I've merged the other PRs, so can close this one out. Thanks for the contribution.

**Pull request closed without merging**
