### PR TITLE
Limited support for plugin navigation

### PR DESCRIPTION
**Pull request by ChristerWendel**
This i basically pull request #126, repackaged to work with the 'develop' branch.

This pull requests add some support for plugin navigation.

The major change is to use the "apps" CLI call to populate the "My apps" menu item, rather than "myapps". This will make the behavior of the menu different.

### CODE REVIEW

**Comment by nikclayton** [comment]
Due to a slightly complicated chain of circumstances, I'm not in a place where I can test this with a player that supports apps at the moment.

So could you let me know what the functionality difference is between the current code and this? Does it make more apps available (or mean that things like the Spotify or Triode app start working)?

**Comment by ChristerWendel** [comment]
Yes, the apps go from totally non-functional to mostly usable.

I've tested the changes with the Google play music and Spotify (Triode) plugins.

Stuff that works:

* Plugin navigation and selection
* Cover art for Google play music plugin

Still not functional:

* Cover art for Spotify (Triode plugin)
* Search

**Comment by nikclayton** [comment]
Great, thanks. This is now part of the 1.4.0-beta-1 release.

**Comment by ChristerWendel** [comment]
Thanks!

**Pull request merged**
