### PR TITLE
doclint disable

### PR DESCRIPTION
**Pull request by gs11**
- Made application movable to SD card
- Turned of doclint (JDK 8) since it caused errors in the eventbus code comments

### CODE REVIEW

**Comment by kaaholst** [comment]
Hi,

Thanks for the pull request. 

I have some concerns about the installLocation attribute. According to [the documentation](https://developer.android.com/guide/topics/data/install-location.html#ShouldNot), it should not be allowed for apps that uses Services, which Squeezer does. Further we may use Alarm Services and/or App Widgets in the future, which also doesn't play well with SD-card.

**Comment by gs11** [comment]
I understand the concern. I guess for Services/Alarms that it could be acceptable with re-registering upon the broadcast intent but not for the widget. If desirable, I'll update the pull request to remove the SD card movability.

**Comment by kaaholst** [comment]
It may not be very important now, but if we later implement a widget, and remove the SD option, what happens for those who did already move it to the SD card. 

I have no experience with SD card moveability, but I definitely think it's safer to leave it out.

**Comment by gs11** [comment]
Commit amended to only include the doclint disable

**Comment by nikclayton** [comment]
I've merged this in. Thanks for the change!

**Pull request closed without merging**
